### ISSUE TITLE
Why not GF(2^64) with clmul?

### ISSUE THREAD

**Issue by gmaxwell** [catid/fp61#1]
Just saw this and your solinas64 repository, -- if your interest is in fast field arith that needs a 64-bit cpu to be fast, why not use clmul?

[feel free to close the issue, this was just an easy (lazy) way to send you a note where other people could comment. :) ]

**Comment by catid** [comment]
Haha yep.  I mean I was mainly interested to find out how these things perform relative to each other.  Best I can tell this direction isn’t worthwhile

**Comment by gmaxwell** [comment]
Ever look into doing a full on bitslice of plain boolean math, and using SSE2 to do 256 field multiplies concurrently like? https://binary.cr.yp.to/bbe-20090604.pdf

**Comment by catid** [comment]
No I haven’t!  Let me start looking into that
